spring:
  application:
    name: expiry-control
  datasource:
    url: jdbc:postgresql://localhost:5433/expiry_control?options=-c%20TimeZone%3DUTC
    username: expiry_user
    password: expiry_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
