-- Esquema inicial de ExpiryControl.
-- Reproduce las tablas que hasta ahora creaba Hibernate, para que una base vacía
-- (por ejemplo, la de producción) quede lista al primer arranque.

create table users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    constraint uk_users_email unique (email)
);

create table products (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(255) not null,
    category varchar(255) not null,
    quantity integer not null,
    expiration_date date not null,
    -- Precio unitario en pesos argentinos (ARS).
    unit_price numeric(12, 2),
    user_id bigint not null,
    constraint fk_products_user foreign key (user_id) references users (id)
);

-- Última notificación que el usuario marcó como leída para cada producto.
create table notification_reads (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    product_id bigint not null,
    category varchar(20) not null,
    expiration_date date not null,
    read_at timestamp(6) with time zone not null,
    constraint uk_notification_reads_user_product unique (user_id, product_id),
    constraint fk_notification_reads_user foreign key (user_id) references users (id) on delete cascade,
    constraint fk_notification_reads_product foreign key (product_id) references products (id) on delete cascade,
    constraint ck_notification_reads_category check (
        category in ('EXPIRED', 'EXPIRES_TODAY', 'WITHIN_3_DAYS', 'WITHIN_7_DAYS', 'WITHIN_14_DAYS')
    )
);

-- Pérdidas por productos vencidos. Se conservan aunque el producto se elimine:
-- en ese caso product_id pasa a null.
create table losses (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    product_id bigint,
    product_name varchar(255) not null,
    quantity integer not null,
    unit_price numeric(12, 2) not null,
    expiration_date date not null,
    total_amount numeric(19, 2) not null,
    recorded_at timestamp(6) with time zone not null,
    constraint uk_losses_product unique (product_id),
    constraint fk_losses_user foreign key (user_id) references users (id) on delete cascade,
    constraint fk_losses_product foreign key (product_id) references products (id) on delete set null
);
